-- Sample data: real Pune localities and well-known outlets. Coordinates are locality-level approximations;
-- ratings, review counts, prices and menus are sample values for the demo (not live data).

INSERT INTO Restaurants (name, area, address, cuisine_type, rating, rating_count, cost_for_two, prep_time_min, lat, lng) VALUES
('Blue Nile','Camp','Bund Garden Road, Camp, Pune','Mughlai & Biryani',4.2,5120,700,30,18.5292,73.8768),
('Shreyas Restaurant','Deccan','Apte Road, Deccan Gymkhana, Pune','Maharashtrian',4.4,3860,450,20,18.5124,73.8328),
('Goodluck Cafe','Deccan','Deccan Gymkhana, Pune','Irani Cafe',4.3,6240,350,15,18.52,73.8326),
('Barbeque Nation','Baner','Baner Road, Baner, Pune','Barbecue & Grill',4.3,7410,1400,35,18.5499,73.7871),
('Malaka Spice','Koregaon Park','North Main Road, Koregaon Park, Pune','Pan-Asian',4.4,4980,1600,35,18.5266,73.892),
('Dragon Palace','Viman Nagar','Nagar Road, Viman Nagar, Pune','Chinese',4.0,2310,900,30,18.5582,73.9055),
('Shivsagar Family Restaurant','Kothrud','Paud Road, Kothrud, Pune','North Indian',4.1,2870,600,25,18.5041,73.8144),
('Punjabi Tadka Dhaba','Wakad','Wakad Road, Wakad, Pune','Punjabi',4.0,1980,550,30,18.5907,73.7559),
('Malvan Katta','Karve Road','Karve Road, Erandwane, Pune','Malvani Seafood',4.2,1750,750,30,18.5048,73.8348),
('Spice Route Kitchen','Magarpatta','Magarpatta City, Hadapsar, Pune','Multi-Cuisine',4.0,1420,900,30,18.5257,73.9168),
('Taco Bell','Viman Nagar','Phoenix Marketcity, Viman Nagar, Pune','Mexican',3.9,6120,500,20,18.5623,73.9166),
('Amigos Cantina','Baner','Baner-Pashan Link Road, Baner, Pune','Mexican',4.1,1240,1100,30,18.5689,73.7804),
('La Cantina','Koregaon Park','Lane 6, Koregaon Park, Pune','Mexican',4.3,1620,1300,30,18.5307,73.8834),
('Taco Fiesta','Deccan','FC Road, Pune','Mexican',4.0,890,700,25,18.5235,73.8412),
('La Dolce Vita','Koregaon Park','Lane 7, Koregaon Park, Pune','Italian',4.3,3340,1800,35,18.5348,73.8997),
('Little Italy','Baner','Baner, Pune','Italian',4.2,2870,1500,30,18.5505,73.7913),
('Napoli Pizzeria','Kalyani Nagar','Kalyani Nagar, Pune','Italian',4.1,1580,1100,25,18.5493,73.8998),
('Ciao Italia','Law College Road','Law College Road, Erandwane, Pune','Italian',4.0,970,1000,30,18.5148,73.8295),
('Vaishali','Deccan','FC Road, Pune','South Indian',4.3,9120,400,15,18.5248,73.8316),
('Roopali','Deccan','FC Road, Pune','South Indian',4.2,5680,350,15,18.5125,73.8353),
('Madras Cafe','Aundh','ITI Road, Aundh, Pune','South Indian',4.1,1420,350,15,18.563,73.8062),
('Dosa Plaza','Hinjewadi','Phase 1, Hinjewadi, Pune','South Indian',3.9,2210,400,20,18.5873,73.7401),
('Sujata Mastani','Sadashiv Peth','Sadashiv Peth, Pune','Desserts',4.4,6980,250,10,18.5173,73.8567),
('Kayani Bakery','Camp','East Street, Camp, Pune','Bakery',4.5,8210,300,10,18.5102,73.8799),
('Naturals Ice Cream','Deccan','JM Road, Deccan Gymkhana, Pune','Ice Cream',4.5,4120,250,8,18.5181,73.8513),
('Baskin Robbins','Baner','Baner Road, Pune','Ice Cream',4.2,2050,300,8,18.5638,73.7808),
('Mad Over Donuts','Kalyani Nagar','Kalyani Nagar, Pune','Desserts',4.0,1560,300,10,18.5558,73.8926),
('Cream & Fudge Dessert Cafe','Kothrud','Kothrud, Pune','Desserts',4.3,1120,350,12,18.5072,73.8157),
('Churn Ice Cream Lab','Viman Nagar','Viman Nagar, Pune','Ice Cream',4.2,860,300,8,18.5613,73.9118),
('Magarpatta Creamery','Magarpatta','Magarpatta City, Hadapsar, Pune','Ice Cream',4.1,740,300,8,18.5039,73.9299),
('Frozen Bowl','Hinjewadi','Phase 1, Hinjewadi, Pune','Ice Cream',3.8,690,300,8,18.5963,73.7411),
('German Bakery','Koregaon Park','North Main Road, Koregaon Park, Pune','Cafe & European',4.4,2450,700,20,18.5362,73.8940),
('Marz-O-Rin','Camp','Bakthiar Plaza, MG Road, Camp, Pune','Bakery & Fast Food',4.5,3120,300,15,18.5175,73.8785),
('George Restaurant','Camp','East Street, Camp, Pune','Mughlai & Biryani',4.3,1890,850,25,18.5145,73.8790),
('Vohuman Cafe','Dhole Patil Road','Millennium Star, Dhole Patil Road, Pune','Irani Cafe & Breakfast',4.6,3800,350,15,18.5320,73.8750),
('Fakruddin Biryani','Kondhwa','Kausar Baugh, Kondhwa, Pune','Mughlai & Biryani',4.4,1420,600,25,18.4780,73.8920),
('Katakirr Misal','Karve Nagar','Near Cummins College, Karve Nagar, Pune','Maharashtrian',4.5,4200,250,10,18.4985,73.8210),
('Bedekar Tea Stall','Narayan Peth','Munjaba Galli, Narayan Peth, Pune','Maharashtrian',4.4,2780,200,10,18.5160,73.8510),
('Chaitanya Paranthas','FC Road','Opposite Fergusson College, FC Road, Pune','North Indian',4.3,2950,450,20,18.5270,73.8415),
('Wadeshwar','FC Road','Near Goodluck Chowk, FC Road, Pune','South Indian',4.5,3600,350,15,18.5225,73.8410),
('Le Plaisir','Deccan','Rajkamal, Prabhat Road, Deccan Gymkhana, Pune','European & Desserts',4.7,3400,1100,25,18.5135,73.8340),
('Mainland China','Senapati Bapat Road','ICC Towers, Senapati Bapat Road, Pune','Chinese & Asian',4.4,2100,1400,30,18.5330,73.8290),
('Siddheshwar Khanaval','Budhwar Peth','Appa Balwant Chowk, Budhwar Peth, Pune','Maharashtrian Non-Veg',4.3,1650,600,20,18.5180,73.8560),
('Maratha Samrat','Kothrud','Near Mayur Colony, Kothrud, Pune','Maharashtrian & Thali',4.6,3100,900,25,18.5040,73.8050),
('Durvankur Dining Hall','Sadashiv Peth','Tilak Road, Sadashiv Peth, Pune','Maharashtrian Thali',4.5,3500,500,15,18.5120,73.8520),
('Arthur''s Theme','Koregaon Park','Vrindavan Park, Lane 6, Koregaon Park, Pune','European & Bistro',4.5,2200,1300,25,18.5375,73.8990),
('Squisito','Koregaon Park','Jewel Square, Koregaon Park Road, Pune','Italian & Pizza',4.4,1750,1200,25,18.5385,73.8915),
('Paasha (JW Marriott)','Senapati Bapat Road','JW Marriott, Senapati Bapat Road, Pune','North Indian & Mughlai',4.7,2800,2400,30,18.5325,73.8310),
('Burger Camp','Camp','Phulgaon Road, East Street, Camp, Pune','Burgers & Fast Food',4.6,4500,350,15,18.5130,73.8805),
('Poona Guest House','Budhwar Peth','Laxmi Road, Budhwar Peth, Pune','Traditional Maharashtrian',4.4,2100,400,15,18.5170,73.8570),
('Yolkshire','Aundh','DP Road, Aundh, Pune','Continental & Breakfast',4.5,1950,650,20,18.5580,73.8070);

INSERT INTO MenuItems (restaurant_id, category, name, description, price, is_veg, is_bestseller) VALUES
(1,'Biryani','Chicken Dum Biryani','Hyderabadi style, with raita',340,false,true),
(1,'Biryani','Mutton Biryani','Slow cooked on dum',420,false,true),
(1,'Biryani','Veg Biryani','Basmati, seasonal vegetables',260,true,false),
(1,'Starters','Chicken Seekh Kebab','Charcoal grilled',290,false,false),
(1,'Starters','Paneer Tikka','Marinated in hung curd',260,true,false),
(1,'Mains','Butter Chicken','Creamy tomato gravy',360,false,true),
(1,'Mains','Dal Bukhara','Overnight simmered black lentils',240,true,false),
(1,'Breads','Butter Naan','Tandoor baked',60,true,false),
(1,'Sides','Boondi Raita','Chilled curd',70,true,false),
(1,'Desserts','Phirni','Chilled rice pudding',110,true,false),
(2,'Thali','Maharashtrian Thali','Unlimited, 2 sabzi, amti, bhakri',380,true,true),
(2,'Snacks','Misal Pav','Kolhapuri style, spicy',140,true,true),
(2,'Snacks','Sabudana Khichdi','With peanuts and lemon',120,true,false),
(2,'Snacks','Batata Vada (2 pc)','With garlic chutney',70,true,true),
(2,'Mains','Thalipeeth','Multigrain, with curd',130,true,false),
(2,'Mains','Amti Bhat','Goda masala dal with rice',160,true,false),
(2,'Desserts','Puran Poli','With ghee',90,true,false),
(2,'Beverages','Solkadhi','Kokum coconut cooler',60,true,false),
(3,'Snacks','Bun Maska','Soft pav, generous butter',55,true,true),
(3,'Mains','Keema Pav','Mutton mince, Irani style',210,false,true),
(3,'Mains','Chicken Berry Pulao','Parsi style',290,false,false),
(3,'Snacks','Egg Omelette Pav','Two eggs, masala',90,false,false),
(3,'Snacks','Cheese Sandwich','Grilled',130,true,false),
(3,'Snacks','Chicken Cutlet','Crumb fried, with kasundi',170,false,true),
(3,'Beverages','Irani Chai','Kadak, in glass',40,true,false),
(3,'Desserts','Caramel Custard','House made',110,true,false),
(4,'Starters','Chicken Tikka','Charcoal grilled',340,false,true),
(4,'Starters','Paneer Tikka','Pudina marinade',300,true,true),
(4,'Starters','Murgh Malai Kebab','Cream and cardamom',360,false,false),
(4,'Starters','Tandoori Prawns','Ajwain marinade',520,false,false),
(4,'Mains','Butter Chicken','With butter naan',380,false,true),
(4,'Mains','Dal Makhani','Cream finished',260,true,false),
(4,'Rice','Veg Biryani','Dum cooked',290,true,false),
(4,'Desserts','Gulab Jamun (2 pc)','Warm',110,true,false),
(5,'Starters','Chicken Satay','Peanut sauce',390,false,false),
(5,'Starters','Crispy Lotus Stem','Honey chilli',360,true,false),
(5,'Soups','Tom Yum Soup (Veg)','Lemongrass, galangal',280,true,false),
(5,'Mains','Thai Green Curry with Chicken','Jasmine rice on the side',480,false,true),
(5,'Mains','Veg Pad Thai','Rice noodles, tamarind',420,true,true),
(5,'Mains','Burmese Khow Suey','Coconut curry noodles, veg',440,true,true),
(5,'Sides','Steamed Jasmine Rice','Fragrant',140,true,false),
(5,'Desserts','Sticky Rice with Mango','Seasonal',260,true,false),
(6,'Soups','Veg Manchow Soup','With crispy noodles',150,true,false),
(6,'Soups','Chicken Hot & Sour Soup','Peppery',190,false,false),
(6,'Starters','Chilli Chicken (Dry)','Wok tossed',320,false,true),
(6,'Starters','Paneer Chilli','Capsicum, spring onion',280,true,true),
(6,'Starters','Honey Chilli Potato','Sesame',220,true,false),
(6,'Mains','Veg Hakka Noodles','Wok fired',220,true,true),
(6,'Mains','Chicken Schezwan Fried Rice','Spicy',280,false,false),
(6,'Mains','Veg Manchurian Gravy','With garlic',250,true,false),
(7,'Mains','Paneer Butter Masala','Rich, mildly sweet',260,true,true),
(7,'Mains','Dal Tadka','Ghee tempering',190,true,false),
(7,'Mains','Kadai Paneer','Capsicum, whole spices',270,true,false),
(7,'Mains','Veg Kolhapuri','Spicy mixed veg',240,true,false),
(7,'Breads','Butter Naan','Tandoor baked',55,true,false),
(7,'Breads','Tandoori Roti','Whole wheat',30,true,false),
(7,'Rice','Jeera Rice','Cumin tempered',160,true,false),
(7,'Beverages','Sweet Lassi','Thick, chilled',90,true,true),
(7,'Desserts','Gulab Jamun (2 pc)','Warm',90,true,false),
(8,'Mains','Butter Chicken','Dhaba style',320,false,true),
(8,'Mains','Chicken Curry','Home style, on the bone',300,false,true),
(8,'Mains','Paneer Tikka Masala','Smoky',270,true,false),
(8,'Mains','Dal Fry','Onion tomato tadka',170,true,false),
(8,'Breads','Amritsari Kulcha','Stuffed aloo',130,true,true),
(8,'Breads','Tandoori Roti','Whole wheat',25,true,false),
(8,'Rice','Jeera Rice','Cumin tempered',140,true,false),
(8,'Beverages','Punjabi Lassi','Sweet, with malai',80,true,false),
(9,'Thali','Chicken Malvani Thali','Vade, curry, rice, solkadhi',380,false,true),
(9,'Seafood','Surmai Fry','Kingfish, rava coated',480,false,true),
(9,'Seafood','Prawns Masala','Malvani masala',450,false,true),
(9,'Seafood','Bombil Fry','Bombay duck',320,false,false),
(9,'Mains','Kombdi Vade','Chicken curry with vade',300,false,false),
(9,'Thali','Veg Thali','Two sabzi, bhakri, rice',260,true,false),
(9,'Sides','Bhakri (2 pc)','Jowar',50,true,false),
(9,'Beverages','Solkadhi','Kokum coconut',70,true,false),
(10,'Starters','Veg Dimsum (6 pc)','Water chestnut, soy',240,true,false),
(10,'Starters','Chicken Tikka','Tandoor grilled',300,false,true),
(10,'Mains','Chicken Biryani','Dum, with raita',320,false,true),
(10,'Mains','Paneer Lababdar','Creamy, tomato',280,true,false),
(10,'Mains','Penne Arrabbiata','Spicy tomato',300,true,false),
(10,'Breads','Butter Naan','Tandoor baked',60,true,false),
(10,'Desserts','Chocolate Mousse','Dark chocolate',160,true,false),
(10,'Beverages','Fresh Lime Soda','Sweet or salted',90,true,false),
(11,'Tacos','Crunchy Taco (Veg)','Beans, lettuce, cheese',129,true,true),
(11,'Tacos','Crunchy Taco (Chicken)','Seasoned chicken',159,false,true),
(11,'Burritos','Burrito Supreme (Veg)','Rice, beans, sour cream',229,true,false),
(11,'Burritos','Chicken Burrito','Grilled chicken',269,false,false),
(11,'Sides','Nachos Supreme','Cheese sauce, salsa',219,true,true),
(11,'Mains','Cheese Quesadilla','Melted cheese',199,true,false),
(11,'Desserts','Cinnamon Twists','Crisp, sugared',89,true,false),
(11,'Beverages','Pepsi (500 ml)','Chilled',80,true,false),
(12,'Starters','Guacamole & Chips','Fresh avocado',280,true,false),
(12,'Starters','Loaded Nachos','Beans, jalapeno, cheese',360,true,true),
(12,'Mains','Chicken Fajitas','Sizzling, tortillas',520,false,true),
(12,'Mains','Veg Quesadilla','Peppers, corn, cheese',380,true,false),
(12,'Bowls','Burrito Bowl (Veg)','Rice, beans, salsa',380,true,true),
(12,'Bowls','Burrito Bowl (Chicken)','Rice, beans, chicken',430,false,false),
(12,'Desserts','Churros','Cinnamon, chocolate dip',240,true,false),
(12,'Beverages','Virgin Margarita','Lime, salt rim',220,true,false),
(13,'Tacos','Chicken Tacos (3 pc)','Pico de gallo',420,false,true),
(13,'Tacos','Mushroom Tacos (3 pc)','Chipotle',380,true,true),
(13,'Mains','Veg Enchiladas','Baked, red sauce',420,true,false),
(13,'Mains','Chicken Enchiladas','Baked, cheese',460,false,false),
(13,'Mains','Chicken Quesadilla','Grilled',410,false,false),
(13,'Starters','Nachos Grande','Beans, cheese',390,true,true),
(13,'Desserts','Tres Leches Cake','Milk soaked',260,true,false),
(13,'Beverages','Mango Iced Tea','Fresh',180,true,false),
(14,'Tacos','Soft Taco (Veg)','Beans, corn, cheese',160,true,true),
(14,'Tacos','Soft Taco (Chicken)','Grilled chicken',190,false,true),
(14,'Wraps','Burrito Wrap (Veg)','Rice, beans',210,true,false),
(14,'Wraps','Burrito Wrap (Chicken)','Rice, chicken',250,false,false),
(14,'Sides','Nachos with Cheese','Salsa dip',180,true,true),
(14,'Bowls','Bean & Rice Bowl','Salsa, guacamole',220,true,false),
(14,'Sides','Salsa Fries','Spicy',150,true,false),
(14,'Desserts','Churros','Chocolate dip',120,true,false),
(15,'Pizza','Margherita Pizza','Wood fired, buffalo mozzarella',480,true,true),
(15,'Pizza','Pepperoni Pizza','Chicken pepperoni',580,false,true),
(15,'Pasta','Penne Alfredo','Creamy, parmesan',460,true,false),
(15,'Pasta','Spaghetti Carbonara','Egg, chicken bacon',520,false,false),
(15,'Mains','Lasagna Bolognese','Baked, slow ragu',560,false,true),
(15,'Starters','Bruschetta','Tomato, basil',320,true,false),
(15,'Starters','Cheese Garlic Bread','Oven baked',260,true,false),
(15,'Desserts','Tiramisu','Classic',360,true,false),
(16,'Pizza','Margherita Pizza','Classic',420,true,true),
(16,'Pizza','Farmhouse Pizza','Onion, capsicum, mushroom',470,true,false),
(16,'Pizza','Chicken Sausage Pizza','Smoked sausage',520,false,true),
(16,'Pasta','Penne Arrabbiata','Spicy tomato',400,true,false),
(16,'Pasta','Chicken Alfredo Pasta','Creamy white sauce',460,false,true),
(16,'Starters','Garlic Bread','Butter, herbs',200,true,false),
(16,'Starters','Cheese Garlic Bread','Mozzarella',240,true,false),
(16,'Desserts','Tiramisu','House recipe',280,true,false),
(17,'Pizza','Margherita Pizza','Tomato, mozzarella',320,true,true),
(17,'Pizza','Peppy Paneer Pizza','Paneer, capsicum',380,true,false),
(17,'Pizza','Chicken Tikka Pizza','Indian twist',420,false,true),
(17,'Pasta','Pink Sauce Pasta','Penne, veg',340,true,true),
(17,'Starters','Garlic Bread','Butter, herbs',160,true,false),
(17,'Desserts','Choco Lava Cake','Molten centre',140,true,false),
(17,'Beverages','Cold Coffee','With ice cream',150,true,false),
(18,'Pasta','Spaghetti Aglio e Olio','Garlic, chilli',360,true,false),
(18,'Pasta','Pesto Fusilli','Basil pesto',390,true,true),
(18,'Mains','Chicken Lasagna','Baked',440,false,true),
(18,'Mains','Veg Lasagna','Spinach, ricotta',400,true,false),
(18,'Mains','Mushroom Risotto','Creamy arborio',420,true,false),
(18,'Pizza','Margherita Pizza','Thin crust',340,true,true),
(18,'Starters','Bruschetta','Tomato, basil',240,true,false),
(18,'Desserts','Tiramisu','Cocoa dusted',240,true,false),
(19,'Dosa','Masala Dosa','Potato bhaji, chutneys',120,true,true),
(19,'Idli','Idli Sambar (2 pc)','Steamed',85,true,true),
(19,'Snacks','Medu Vada (2 pc)','Crisp',90,true,false),
(19,'Dosa','Rava Uttapam','Onion, tomato',130,true,false),
(19,'Snacks','Sabudana Wada','With peanut chutney',90,true,true),
(19,'Snacks','Misal Pav','Pune style',120,true,false),
(19,'Beverages','Filter Coffee','Strong, frothy',50,true,false),
(19,'Desserts','Sheera','Warm semolina',70,true,false),
(20,'Dosa','Rava Masala Dosa','Crisp, onion',140,true,false),
(20,'Dosa','Paper Dosa','Extra thin',130,true,false),
(20,'Dosa','Mysore Masala Dosa','Red chutney',150,true,true),
(20,'Idli','Idli Vada Combo','Sambar, chutney',110,true,true),
(20,'Dosa','Onion Uttapam','Thick',130,true,false),
(20,'Rice','Curd Rice','With pickle',110,true,false),
(20,'Beverages','Filter Coffee','Strong',55,true,false),
(20,'Desserts','Kesari Bhat','Saffron semolina',60,true,false),
(21,'Dosa','Ghee Roast Dosa','Crisp, ghee',150,true,true),
(21,'Idli','Podi Idli','Ghee, gunpowder',120,true,true),
(21,'Dosa','Set Dosa (3 pc)','Soft, with saagu',130,true,false),
(21,'Meals','South Indian Meals','Rice, sambar, rasam, poriyal',220,true,false),
(21,'Rice','Bisi Bele Bath','Spiced lentil rice',170,true,false),
(21,'Rice','Curd Rice','Tempered',100,true,false),
(21,'Beverages','Filter Coffee','Decoction',60,true,false),
(21,'Desserts','Payasam','Vermicelli',80,true,false),
(22,'Dosa','Cheese Masala Dosa','Loaded with cheese',180,true,true),
(22,'Dosa','Schezwan Dosa','Indo-Chinese twist',190,true,false),
(22,'Dosa','Paneer Chilli Dosa','Stuffed',210,true,true),
(22,'Dosa','Plain Dosa','Crisp',110,true,false),
(22,'Idli','Idli Sambar (3 pc)','Steamed',90,true,false),
(22,'Dosa','Pav Bhaji Dosa','Mumbai fusion',190,true,false),
(22,'Dosa','Mysore Sada Dosa','Red chutney',140,true,true),
(22,'Beverages','Filter Coffee','Hot',60,true,false),
(23,'Mastani','Kesar Pista Mastani','Thick shake, ice cream, dry fruits',170,true,true),
(23,'Mastani','Mango Mastani','Seasonal alphonso',190,true,true),
(23,'Mastani','Chocolate Mastani','With choco chips',160,true,false),
(23,'Snacks','Sabudana Vada (2 pc)','Crisp, peanut chutney',100,true,true),
(23,'Desserts','Fruit Salad with Ice Cream','Seasonal fruits',150,true,false),
(23,'Desserts','Falooda','Rose syrup, vermicelli',160,true,false),
(23,'Beverages','Thick Shake (Butterscotch)','Chilled',130,true,false),
(24,'Biscuits','Shrewsbury Biscuits (250 g)','Buttery, melt in mouth',140,true,true),
(24,'Cakes','Mawa Cake (slice)','Soft, cardamom',60,true,true),
(24,'Cakes','Fruit Cake (slice)','Rich, spiced',70,true,false),
(24,'Biscuits','Ginger Biscuits (250 g)','Crunchy',130,true,false),
(24,'Snacks','Khari (250 g)','Flaky puff',90,true,false),
(24,'Snacks','Chicken Puff','Warm, baked',60,false,false),
(24,'Snacks','Veg Puff','Warm, baked',45,true,false),
(24,'Desserts','Chocolate Walnut Brownie','Fudgy',90,true,true),
(25,'Scoops','Tender Coconut (1 scoop)','Real coconut pieces',90,true,true),
(25,'Scoops','Sitaphal (1 scoop)','Custard apple, seasonal',100,true,true),
(25,'Scoops','Roasted Almond (1 scoop)','Crunchy',100,true,false),
(25,'Sundaes','Chocolate Sundae','Fudge sauce',190,true,false),
(25,'Sundaes','Fresh Fruit Sundae','Seasonal fruits',210,true,true),
(25,'Sundaes','Death by Chocolate','Brownie, choco sauce',240,true,false),
(25,'Scoops','Kulfi (1 scoop)','Malai',90,true,false),
(26,'Scoops','Single Scoop','Choice of flavour',110,true,true),
(26,'Scoops','Double Scoop','Choice of two flavours',200,true,false),
(26,'Sundaes','Hot Fudge Sundae','Vanilla, hot fudge',250,true,true),
(26,'Sundaes','Brownie Sundae','Warm brownie',290,true,true),
(26,'Desserts','Banana Split','Three scoops',320,true,false),
(26,'Beverages','Oreo Milkshake','Thick',240,true,false),
(26,'Cones','Waffle Cone Scoop','Fresh waffle',150,true,false),
(27,'Donuts','Glazed Donut','Classic',70,true,true),
(27,'Donuts','Choco Filled Donut','Chocolate cream',90,true,true),
(27,'Donuts','Boston Cream Donut','Custard filled',95,true,false),
(27,'Donuts','Strawberry Sprinkles','Iced',85,true,false),
(27,'Boxes','Donut Box (6 pc)','Assorted',470,true,true),
(27,'Desserts','Chocolate Brownie','Warm',110,true,false),
(27,'Beverages','Cold Coffee','Chilled',150,true,false),
(27,'Beverages','Hot Chocolate','Rich',160,true,false),
(28,'Desserts','Brownie with Ice Cream','Sizzling',210,true,true),
(28,'Desserts','Belgian Waffle','Nutella, banana',220,true,true),
(28,'Crepes','Nutella Crepe','Hazelnut spread',230,true,true),
(28,'Jars','Red Velvet Jar','Cream cheese',190,true,false),
(28,'Jars','Tiramisu Jar','Coffee soaked',200,true,false),
(28,'Desserts','Cheesecake Slice','New York style',240,true,false),
(28,'Beverages','Oreo Shake','Thick',200,true,false),
(29,'Scoops','Salted Caramel (1 scoop)','Small batch',120,true,true),
(29,'Scoops','Belgian Chocolate (1 scoop)','Rich',120,true,true),
(29,'Scoops','Filter Coffee (1 scoop)','South Indian coffee',130,true,false),
(29,'Sundaes','Nutella Sundae','Hazelnut',250,true,true),
(29,'Desserts','Kulfi Falooda','Rose, vermicelli',200,true,false),
(29,'Beverages','Oreo Shake','Thick',210,true,false),
(29,'Sundaes','Brownie Sundae','Warm brownie',260,true,false),
(30,'Scoops','Alphonso Mango (1 scoop)','Seasonal',130,true,true),
(30,'Scoops','Butterscotch (1 scoop)','Crunchy praline',100,true,false),
(30,'Scoops','Choco Chip (1 scoop)','Dark chips',110,true,false),
(30,'Sundaes','Fruit & Nut Sundae','Dry fruits',230,true,true),
(30,'Desserts','Waffle with Scoop','Warm waffle',220,true,true),
(30,'Beverages','Chocolate Shake','Thick',190,true,false),
(30,'Desserts','Kulfi Stick','Malai',90,true,false),
(31,'Scoops','Vanilla (1 scoop)','Classic',90,true,false),
(31,'Sundaes','Chocolate Brownie Sundae','Warm brownie',240,true,true),
(31,'Desserts','Rabri Falooda','Rose, rabri',180,true,true),
(31,'Scoops','Butterscotch (1 scoop)','Crunchy',100,true,false),
(31,'Beverages','Cold Coffee with Ice Cream','Chilled',170,true,false),
(31,'Beverages','Oreo Shake','Thick',200,true,false),
(31,'Desserts','Mango Kulfi','Malai',100,true,true),
(31,'Sundaes','Waffle Sundae','Waffle, scoop, sauce',230,true,false),
(32,'Beverages','German Cappuccino','Rich espresso with frothy steamed milk',160,true,true),
(32,'Cafe','Apple Cinnamon Pie','Warm spiced apple pie with crumb topping',190,true,true),
(32,'Breakfast','Cheese Omelette with Toast','Fluffy 3-egg omelette served with herb butter toast',220,false,false),
(32,'Main course','Classic Chicken Lasagna','Layers of minced chicken, pasta sheets and melted cheese',340,false,true),
(32,'Bakery','Almond Croissant','Flaky butter croissant baked with almond frangipane',150,true,false),
(32,'Salads','Mediterranean Greek Salad','Crisp cucumbers, cherry tomatoes, olives and feta cheese',240,true,false),
(33,'Sandwiches','Chutney Cheese Sandwich','Iconic green mint chutney with grated cheese in soft bread',80,true,true),
(33,'Sandwiches','Chicken Sandwich','Shredded chicken with classic seasoned house mayonnaise',110,false,true),
(33,'Fast Food','Macaroni in White Sauce','Classic comforting baked macaroni in creamy bechamel',140,true,false),
(33,'Beverages','Cold Coffee','Creamy chilled brewed coffee',90,true,true),
(33,'Bakery','Rich Plum Cake Slice','Traditional spiced fruit and plum cake',75,true,false),
(33,'Bakery','Chicken Puff','Crispy flaky pastry stuffed with seasoned chicken keema',60,false,false),
(34,'Biryani','George Special Mutton Dum Biryani','Slow-cooked fragrant basmati rice with tender spiced mutton',380,false,true),
(34,'Biryani','Chicken Dum Biryani','Traditional Persian-style chicken dum biryani with raita',320,false,true),
(34,'Starters','Mutton Seekh Kebab','Minced mutton skewers chargrilled in tandoor',310,false,false),
(34,'Curries','Butter Chicken','Tender tandoori chicken simmered in rich makhani gravy',330,false,true),
(34,'Breads','Butter Garlic Naan','Crispy leavened tandoor bread brushed with butter and garlic',65,true,false),
(34,'Desserts','Caramel Custard','Silky egg custard with golden caramel syrup',120,false,false),
(35,'Breakfast','Bun Maska','Warm soft bun generously slathered with salted butter',50,true,true),
(35,'Breakfast','Cheese Omelette (Double)','Double egg omelette topped with grated processed cheese',130,false,true),
(35,'Breakfast','Irani Chai','Signature slow-brewed sweetened thick milk tea',35,true,true),
(35,'Breakfast','Toast Butter Jam','Crispy browned toast with butter and mixed fruit jam',60,true,false),
(35,'Fast Food','Egg Bhurji Pav','Spicy scrambled eggs with green chilies, served with pav',110,false,false),
(36,'Biryani','Kolkata Style Chicken Biryani','Fragrant long grain rice with chicken piece and spiced potato',240,false,true),
(36,'Biryani','Mutton Awadhi Dum Biryani','Slow-cooked mutton biryani served with mirchi ka salan',340,false,true),
(36,'Starters','Chicken Tikka Dry','Charcoal grilled spicy chicken chunks',220,false,false),
(36,'Curries','Chicken Korma','Mild cashew and yogurt based chicken gravy',260,false,false),
(36,'Breads','Rumali Roti','Thin soft handkerchief flatbread',35,true,false),
(37,'Misal','Tikha Kolhapuri Misal Pav','Extra spicy sprouts curry topped with farsan, onions and lemon',110,true,true),
(37,'Misal','Medium Spicy Misal Pav','Balanced aromatic rassa with farsan, served with 2 pav',110,true,true),
(37,'Misal','Light Misal Pav','Mild spiced sprouted moth beans with crunchy farsan',110,true,false),
(37,'Sides','Extra Pav (Pair)','Two fresh soft pav buns',20,true,false),
(37,'Beverages','Taak (Spiced Buttermilk)','Cooling curd buttermilk tempered with ginger and cumin',35,true,false),
(37,'Desserts','Gulab Jamun (2 pcs)','Warm soft khoya dumplings soaked in sugar syrup',60,true,false),
(38,'Misal','Bedekar Puneri Misal with Bread','Signature sweet-and-spicy Puneri misal with bread slices',100,true,true),
(38,'Sides','Extra Bread Slice (2 pcs)','Two thick slices of white bread',20,true,false),
(38,'Beverages','Special Masala Chai','Strong cardamom ginger flavored tea',25,true,true),
(38,'Snacks','Pohe','Flattened rice tempered with mustard, peanuts, and turmeric',45,true,false),
(38,'Snacks','Upma','Roasted semolina cooked with mild green chillies and ghee',45,true,false),
(39,'Parathas','Aloo Cheese Paratha','Whole wheat flatbread stuffed with spiced potatoes and cheese',130,true,true),
(39,'Parathas','Paneer Pudina Paratha','Flatbread stuffed with cottage cheese and fresh mint',140,true,true),
(39,'Parathas','Gobi Garlic Paratha','Spiced cauliflower stuffing with garlic butter',120,true,false),
(39,'Meals','Dal Makhani Combo','Black lentils slow cooked with cream, served with 2 parathas',210,true,false),
(39,'Beverages','Sweet Punjabi Lassi','Thick churned sweet yogurt topped with malai',80,true,false),
(40,'Dosas','Ghee Roast Masala Dosa','Crispy dosa roasted in desi ghee stuffed with potato masala',135,true,true),
(40,'Snacks','Wada Sambar (2 pcs)','Crispy lentil fritters soaked in hot tangy sambar',85,true,true),
(40,'Snacks','Steamed Idli Sambar (2 pcs)','Pillowy soft rice cakes with coconut chutney and sambar',75,true,false),
(40,'Snacks','Appe with Chutney','Crispy golden batter dumplings served with coconut chutney',95,true,false),
(40,'Beverages','Filter Coffee','Traditional South Indian frothy chicory coffee',45,true,true),
(41,'Pastas','Spinach Tagliatelle in Cream Sauce','Handmade spinach pasta in garlic cream parmesan reduction',380,true,true),
(41,'Mains','Roast Chicken with Herb Jus','Tender oven-roasted chicken breast with mash and roast jus',440,false,true),
(41,'Desserts','Espresso Panna Cotta','Silky coffee panna cotta with dark chocolate drizzle',260,false,false),
(41,'Desserts','Hazelnut Mousse Slice','Decadent chocolate hazelnut mousse cake',280,true,true),
(41,'Sandwiches','Smoked Chicken Crepe','Savory French crepe stuffed with smoked chicken and sundried tomato',330,false,false),
(42,'Dim Sum','Chicken Siu Mai','Steamed open-faced dumplings with seasoned minced chicken',295,false,true),
(42,'Dim Sum','Edamame & Truffle Dumpling','Translucent steamed crystal dumplings with edamame puree',320,true,true),
(42,'Mains','Kung Pao Chicken','Wok-tossed chicken with dry red chilies, Sichuan pepper and peanuts',420,false,true),
(42,'Noodles','Hakka Noodles Vegetable','Wok-tossed noodles with shredded bell peppers, cabbage and scallions',310,true,false),
(42,'Rice','Yang Chow Fried Rice','Classic wok fried rice with egg, chicken and prawns',360,false,false),
(43,'Thali','Special Mutton Thali','Kolhapuri mutton sukkha, tambra rassa, pandhra rassa, 2 bhakri',380,false,true),
(43,'Thali','Chicken Kolhapuri Thali','Spicy chicken gravy, tambda rassa, jowar bhakri and indrayani bhat',290,false,true),
(43,'Sides','Extra Tambda Rassa Bowl','Signature fiery red spicy Kolhapuri mutton bone broth',60,false,false),
(43,'Sides','Extra Pandhra Rassa Bowl','Mild aromatic white coconut and poppy seed soup broth',60,false,false),
(43,'Breads','Jowar Bhakri (1 pc)','Fresh hot hand-flattened sorghum bread',25,true,false),
(44,'Thali','Mutton Fry Thali','Pan-fried spiced goat meat with rich onion-coconut masala and bhakri',420,false,true),
(44,'Thali','Surmai Fish Fry Thali','Semolina crusted Kingfish fry with coconut solkadhi and rice',480,false,true),
(44,'Starters','Chicken Sukka Plate','Semi-dry spiced village style roasted chicken',280,false,false),
(44,'Beverages','Solkadhi Glass','Refreshing digestive drink made with kokum and coconut milk',65,true,false),
(44,'Rice','Indrayani Rice with Ghee','Sticky aromatic Maharashtrian rice topped with pure ghee',120,true,false),
(45,'Thali','Unlimited Maharashtrian Veg Thali','Puri, chapatis, 3 subzis, maharashtrian amti, dal, rice, sweet',240,true,true),
(45,'Sweets','Puran Poli with Ghee (1 pc)','Traditional sweet flatbread filled with spiced jaggery dal',65,true,true),
(45,'Sweets','Shrikhand Cup','Strained sweetened saffron and cardamom yogurt',70,true,false),
(45,'Snacks','Kothimbir Vadi (4 pcs)','Crispy steamed coriander and gram flour cakes',85,true,false),
(45,'Beverages','Mattha (Spiced Buttermilk)','Cumin, green chili and coriander spiced curd drink',40,true,false),
(46,'Mains','Napoleon Grilled Chicken','Char-grilled chicken breast with mushroom pepper sauce',450,false,true),
(46,'Mains','Alexander Lamb Chops','Rosemary garlic roasted lamb chops with mashed potatoes',560,false,true),
(46,'Pastas','Penne Quattro Formaggi','Penne pasta in rich four-cheese reduction with toasted herbs',390,true,false),
(46,'Salads','Warm Goat Cheese Salad','Mixed mesclun greens with baked goat cheese and balsamic',320,true,false),
(46,'Desserts','Tiramisu Classico','Coffee soaked savoiardi with mascarpone zabaglione',260,false,false),
(47,'Pizza','Margherita Autentica (11 inch)','San Marzano tomato sauce, fresh buffalo mozzarella, fresh basil',420,true,true),
(47,'Pizza','Quattro Stagioni Pizza','Mushrooms, artichokes, black olives and sun-dried tomatoes',490,true,true),
(47,'Pastas','Fettuccine Alfredo with Truffle','Handmade ribbon pasta with parmesan butter cream and truffle oil',440,true,false),
(47,'Starters','Bruschetta al Pomodoro','Toasted rustic bread with diced plum tomatoes, garlic and olive oil',260,true,false),
(47,'Desserts','Panna Cotta al Caramello','Velvety cooked cream with rich salted caramel sauce',230,true,false),
(48,'Starters','Galouti Kebab','Melt-in-mouth smoked lamb patties served with ulte tawe ka paratha',620,false,true),
(48,'Starters','Paneer Tikka Paashiyana','Clay oven chargrilled paneer cubes with pomegranate mint glaze',480,true,true),
(48,'Curries','Dal Paasha','Slow-cooked overnight black lentils with butter and cream',450,true,false),
(48,'Curries','Murgh Awadhi Korma','Chicken braised in rich cashew, saffron and rosewater gravy',580,false,false),
(48,'Breads','Taftan Naan','Rich saffron leavened tandoori bread with nigella seeds',120,true,false),
(49,'Burgers','King Burger (Chicken)','Massive double-patty chicken burger with special secret mayo spread',160,false,true),
(49,'Burgers','Jumbo Veg Burger','Crispy spiced vegetable cutlet burger with crunchy lettuce',110,true,true),
(49,'Burgers','Fillet Fish Burger','Crispy golden fried fish fillet with tartare sauce',180,false,false),
(49,'Sides','Crinkle Cut French Fries','Deep fried crinkle fries dusted with peri peri seasoning',80,true,false),
(49,'Beverages','Chilled Cold Coffee Shake','Sweet thick cold coffee in classic tall glass',70,true,false),
(50,'Snacks','Thalipeeth with White Butter','Multi-grain spiced pancake served with fresh white loni and thecha',95,true,true),
(50,'Snacks','Batata Vada (2 pcs)','Golden spiced potato fritters served with dry garlic chutney',60,true,true),
(50,'Snacks','Kanda Bhaji','Crispy deep-fried onion pakoras with fried green chilies',70,true,false),
(50,'Meals','Pithla Bhakri Meal','Traditional spiced gram flour curry with hot jowar bhakri and thecha',140,true,false),
(50,'Beverages','Piyush Glass','Rich sweet festive drink made of shrikhand and buttermilk',65,true,false),
(51,'Breakfast','Classic Eggs Benedict','Poached eggs on buttered muffin with smoked ham and hollandaise',270,false,true),
(51,'Breakfast','Fluffy Pancakes with Maple Syrup','Stack of three buttermilk pancakes with butter and syrup',210,true,true),
(51,'Breakfast','Shakshuka with Pita','Eggs poached in a spiced tomato, pepper and onion sauce',250,false,false),
(51,'Beverages','Hazelnut Cold Brew','Steeped dark roast cold brew with roasted hazelnut syrup',160,true,false),
(51,'Sandwiches','Grilled Cheese & Mushroom Panini','Toasted sourdough with sautéed button mushrooms and cheddar',220,true,false);

INSERT INTO DeliveryPartners (name, phone, lat, lng, zone, vehicle_type, vehicle_no, rating, total_deliveries) VALUES
('Rahul Patil','9822011201',18.523,73.839,'Deccan','Bike','MH12 KP 4821',4.7,1284),
('Amit Shinde','9822011202',18.5331,73.8495,'Shivajinagar','Bike','MH12 LQ 1093',4.5,962),
('Sneha Kulkarni','9822011203',18.5103,73.8093,'Kothrud','Scooter','MH12 TR 7754',4.8,1530),
('Vikas More','9822011204',18.5084,73.8331,'Karve Road','Bike','MH12 NB 3308',4.4,701),
('Imran Sheikh','9822011205',18.5156,73.8816,'Camp','Bike','MH12 HC 5512',4.6,1105),
('Pooja Jadhav','9822011206',18.5295,73.8962,'Koregaon Park','Scooter','MH12 UV 2267',4.9,1820),
('Sagar Gaikwad','9822011207',18.5484,73.9099,'Kalyani Nagar','Bike','MH12 RD 9041',4.3,588),
('Nikhil Deshmukh','9822011208',18.5732,73.9106,'Viman Nagar','Bike','MH12 WX 6135',4.5,873),
('Kiran Pawar','9822011209',18.5572,73.7897,'Baner','Bike','MH14 GH 4470',4.6,1342),
('Akash Thorat','9822011210',18.5504,73.8064,'Aundh','Scooter','MH14 JK 8826',4.4,640),
('Ganesh Kale','9822011211',18.5862,73.7329,'Hinjewadi','Bike','MH14 MN 1729',4.2,477),
('Rohit Bhosale','9822011212',18.5919,73.7653,'Wakad','Bike','MH14 PQ 3958',4.5,752),
('Shubham Jagtap','9822011213',18.5091,73.922,'Magarpatta','Bike','MH12 SY 7204',4.6,1019),
('Tejas Chavan','9822011214',18.5093,73.8569,'Sadashiv Peth','Scooter','MH12 AZ 6613',4.7,1177);

-- Idempotent restaurant image mapping: relative path with no leading slash and no host
UPDATE Restaurants SET photo_url = 'images/r' || restaurant_id || '.jpg' WHERE photo_url IS NULL;
